# ============================================================
# BASE DE CONNAISSANCES POUR LE RAG
# Fiches courtes et factuellement vérifiées, par matière.
# ============================================================

KNOWLEDGE_BASE = [
    # ---------------- MATHS ----------------
    {"subject": "Math", "title": "Pythagorean theorem",
     "content": "The Pythagorean theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the other two sides: a^2 + b^2 = c^2."},
    {"subject": "Math", "title": "Derivative",
     "content": "A derivative measures how a function changes as its input changes. It represents the slope of the tangent line to the function's graph at a given point."},
    {"subject": "Math", "title": "Integral",
     "content": "An integral represents the area under the curve of a function. It is the reverse operation of differentiation."},
    {"subject": "Math", "title": "Prime number",
     "content": "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself. Examples include 2, 3, 5, 7, 11."},
    {"subject": "Math", "title": "Pi",
     "content": "Pi (denoted by the Greek letter pi) is the ratio of a circle's circumference to its diameter, approximately equal to 3.14159."},
    {"subject": "Math", "title": "Matrix",
     "content": "A matrix is a rectangular array of numbers arranged in rows and columns, used to represent linear transformations and solve systems of linear equations."},
    {"subject": "Math", "title": "Probability",
     "content": "Probability is a measure of the likelihood that an event will occur, expressed as a number between 0 (impossible) and 1 (certain)."},

    # ---------------- PHYSIQUE ----------------
    {"subject": "Physics", "title": "Newton's first law",
     "content": "Newton's first law states that an object at rest stays at rest, and an object in motion stays in motion at constant velocity, unless acted upon by an external force."},
    {"subject": "Physics", "title": "Newton's second law",
     "content": "Newton's second law states that force equals mass times acceleration (F = m x a)."},
    {"subject": "Physics", "title": "Ohm's law",
     "content": "Ohm's law states that the current through a conductor is directly proportional to the voltage and inversely proportional to the resistance: V = I x R."},
    {"subject": "Physics", "title": "Energy conservation",
     "content": "The law of conservation of energy states that energy cannot be created or destroyed, only transformed from one form to another."},
    {"subject": "Physics", "title": "Speed of light",
     "content": "The speed of light in a vacuum is approximately 299,792 kilometers per second (about 300,000 km/s), the fastest speed possible in the universe."},
    {"subject": "Physics", "title": "Gravity",
     "content": "Gravity is the force of attraction between two masses. On Earth, gravitational acceleration is approximately 9.81 meters per second squared."},
    {"subject": "Physics", "title": "Electric current",
     "content": "Electric current is the flow of electric charge, measured in amperes (A). It flows through a conductor when there is a difference in electric potential."},
    {"subject": "Physics", "title": "Wavelength and frequency",
     "content": "Wavelength is the distance between two consecutive peaks of a wave, while frequency is the number of wave cycles per second, measured in hertz (Hz). Speed = wavelength x frequency."},

    # ---------------- GEOGRAPHIE ----------------
    {"subject": "Geography", "title": "Continents",
     "content": "There are seven continents on Earth: Africa, Antarctica, Asia, Australia, Europe, North America, and South America."},
    {"subject": "Geography", "title": "Largest ocean",
     "content": "The Pacific Ocean is the largest and deepest ocean on Earth, covering about one-third of the planet's surface."},
    {"subject": "Geography", "title": "Longest river",
     "content": "The Nile River, located in Africa, is generally considered the longest river in the world, flowing through Egypt, Sudan, and other countries."},
    {"subject": "Geography", "title": "Highest mountain",
     "content": "Mount Everest, located in the Himalayas on the border of Nepal and China (Tibet), is the highest mountain above sea level at 8,849 meters."},
    {"subject": "Geography", "title": "Sahara Desert",
     "content": "The Sahara is the largest hot desert in the world, covering most of North Africa, including parts of Tunisia, Algeria, Libya, and Morocco."},
    {"subject": "Geography", "title": "Mediterranean Sea",
     "content": "The Mediterranean Sea is a sea connected to the Atlantic Ocean, surrounded by Europe, North Africa, and the Middle East. Tunisia has a long Mediterranean coastline."},

    # ---------------- CIVILISATION / HISTOIRE ----------------
    {"subject": "Civilization", "title": "Ancient Carthage",
     "content": "Carthage was an ancient civilization located in what is now Tunisia, founded by the Phoenicians around the 9th century BC. It became a major power in the Mediterranean before being destroyed by Rome in 146 BC."},
    {"subject": "Civilization", "title": "Ancient Egypt",
     "content": "Ancient Egypt was a civilization along the Nile River, known for its pyramids, pharaohs, and hieroglyphic writing system, flourishing for over 3000 years."},
    {"subject": "Civilization", "title": "Roman Empire",
     "content": "The Roman Empire was one of the largest empires in ancient history, centered in Rome, spanning from Britain to North Africa and the Middle East at its peak."},
    {"subject": "Civilization", "title": "Industrial Revolution",
     "content": "The Industrial Revolution, starting in Britain in the late 18th century, was a period of major industrialization and innovation, transitioning from manual production to machine manufacturing."},
    {"subject": "Civilization", "title": "Tunisian independence",
     "content": "Tunisia gained independence from France on March 20, 1956, ending the French protectorate that had lasted since 1881."},
    {"subject": "Civilization", "title": "Internet invention",
     "content": "The internet originated from ARPANET, a project developed by the US Department of Defense in the late 1960s, and evolved into the modern global network we use today."},

    # ---------------- ELECTRONIQUE / TELECOMS ----------------
    {"subject": "Electronics", "title": "Voltage",
     "content": "Voltage is the electric potential difference between two points, measured in volts (V). It represents the force that pushes electric charge through a circuit."},
    {"subject": "Electronics", "title": "Resistance",
     "content": "Electrical resistance is the opposition to the flow of electric current in a conductor, measured in ohms. It is calculated using Ohm's law: R = V / I."},
    {"subject": "Electronics", "title": "Capacitor",
     "content": "A capacitor is an electronic component that stores electrical energy in an electric field, made of two conductive plates separated by an insulator, measured in farads (F)."},
    {"subject": "Electronics", "title": "Transistor",
     "content": "A transistor is a semiconductor device used to amplify or switch electronic signals. It is a fundamental building block of modern electronic devices and integrated circuits."},
    {"subject": "Electronics", "title": "Signal modulation",
     "content": "Modulation is the process of varying a carrier signal's properties (amplitude, frequency, or phase) to encode information for transmission, used in radio and telecommunications."},
    {"subject": "Electronics", "title": "Analog vs digital signal",
     "content": "An analog signal is continuous and can take any value over a range, while a digital signal is discrete, represented as binary values (0 and 1)."},
    {"subject": "Electronics", "title": "Bandwidth",
     "content": "Bandwidth is the range of frequencies a communication channel can carry, or the maximum data transfer rate of a network connection, typically measured in hertz or bits per second."},
    {"subject": "Electronics", "title": "Antenna",
     "content": "An antenna is a device that converts electrical signals into electromagnetic waves for wireless transmission, and vice versa for reception."},
    {"subject": "Electronics", "title": "Diode",
     "content": "A diode is a semiconductor component that allows electric current to flow in only one direction, commonly used for rectification (converting AC to DC)."},
    {"subject": "Electronics", "title": "Microcontroller",
     "content": "A microcontroller is a compact integrated circuit containing a processor, memory, and input/output peripherals, used to control electronic devices such as PIC or Arduino boards."},
    {"subject": "Electronics", "title": "Analog-to-digital converter (ADC)",
     "content": "An ADC (Analog-to-Digital Converter) converts a continuous analog signal into a discrete digital value, allowing microcontrollers and computers to process real-world signals."},
    {"subject": "Electronics", "title": "Multiplexer",
     "content": "A multiplexer (MUX) is a digital circuit that selects one of several input signals and forwards it to a single output line, based on selector control signals."},
    {"subject": "Electronics", "title": "Flip-flop",
     "content": "A flip-flop is a basic digital circuit that stores one bit of binary data, used as a building block for registers, counters, and memory in digital electronics."},

    # ---------------- RESEAUX / TELECOMS AVANCE ----------------
    {"subject": "Networking", "title": "IP address",
     "content": "An IP address is a unique numerical identifier assigned to each device on a network, used to route data between devices using the Internet Protocol."},
    {"subject": "Networking", "title": "TCP/IP",
     "content": "TCP/IP is the fundamental suite of communication protocols used on the internet, with TCP ensuring reliable data delivery and IP handling addressing and routing."},
    {"subject": "Networking", "title": "OSI model",
     "content": "The OSI model is a conceptual framework that divides network communication into seven layers: Physical, Data Link, Network, Transport, Session, Presentation, and Application."},
    {"subject": "Networking", "title": "DNS",
     "content": "DNS (Domain Name System) translates human-readable domain names (like google.com) into numerical IP addresses that computers use to identify each other."},
    {"subject": "Networking", "title": "Router",
     "content": "A router is a networking device that forwards data packets between different computer networks, directing traffic on the internet and local networks."},
    {"subject": "Networking", "title": "LAN vs WAN",
     "content": "A LAN (Local Area Network) connects devices within a small area like a home or office, while a WAN (Wide Area Network) spans large geographic areas, such as the internet."},
    {"subject": "Networking", "title": "Mobile network generations",
     "content": "Mobile network generations (2G, 3G, 4G, 5G) represent successive advances in wireless technology, each offering higher data speeds and lower latency than the previous one."},
    {"subject": "Networking", "title": "Optical fiber",
     "content": "Optical fiber is a thin strand of glass or plastic that transmits data as pulses of light, offering very high bandwidth and low signal loss over long distances."},

    # ---------------- IA / MACHINE LEARNING ----------------
    {"subject": "Artificial Intelligence", "title": "Machine learning",
     "content": "Machine learning is a field of artificial intelligence where computer systems learn patterns from data to make predictions or decisions, without being explicitly programmed for each task."},
    {"subject": "Artificial Intelligence", "title": "Artificial intelligence",
     "content": "Artificial intelligence (AI) is the broad field of computer science focused on building systems that can perform tasks typically requiring human intelligence, such as reasoning, learning, perception, and decision-making."},
    {"subject": "Artificial Intelligence", "title": "AI, ML and DL relationship",
     "content": "Artificial intelligence (AI) is the broadest concept: building systems that mimic human intelligence. Within AI lies machine learning (ML), where systems improve through experience with data. Within ML lies deep learning (DL), which relies on multi-layered neural networks."},
    {"subject": "Artificial Intelligence", "title": "Neural network",
     "content": "A neural network is a machine learning model inspired by the human brain, made of layers of interconnected nodes (neurons) that process and learn from data."},
    {"subject": "Artificial Intelligence", "title": "Deep learning",
     "content": "Deep learning is a subset of machine learning that uses neural networks with many layers to automatically learn complex patterns from large amounts of data."},
    {"subject": "Artificial Intelligence", "title": "Transformer architecture",
     "content": "The Transformer is a neural network architecture introduced in 2017, based on the attention mechanism, forming the foundation of modern language models like GPT and BERT."},
    {"subject": "Artificial Intelligence", "title": "Overfitting",
     "content": "Overfitting occurs when a machine learning model learns the training data too closely, including its noise, resulting in poor performance on new, unseen data."},
    {"subject": "Artificial Intelligence", "title": "Tokenization",
     "content": "Tokenization is the process of splitting text into smaller units (tokens), such as words or subwords, which language models use as their basic input units."},
    {"subject": "Artificial Intelligence", "title": "Fine-tuning",
     "content": "Fine-tuning is the process of taking a pre-trained model and further training it on a smaller, specific dataset to adapt it to a particular task."},
    {"subject": "Artificial Intelligence", "title": "Large Language Model (LLM)",
     "content": "A Large Language Model (LLM) is a type of AI model trained on massive amounts of text data, capable of understanding and generating human-like language, such as GPT or Claude."},

    # ---------------- SIGNAL / DSP (Traitement du Signal) ----------------
    {"subject": "Signal Processing", "title": "Fourier transform",
     "content": "The Fourier transform is a mathematical technique that decomposes a signal into its constituent frequencies, converting a signal from the time domain to the frequency domain."},
    {"subject": "Signal Processing", "title": "Digital Signal Processor (DSP)",
     "content": "A DSP (Digital Signal Processor) is a specialized microprocessor optimized for processing digital signals in real time, such as audio, video, or communication signals."},
    {"subject": "Signal Processing", "title": "Sampling theorem",
     "content": "The Nyquist-Shannon sampling theorem states that a continuous signal must be sampled at a rate at least twice its highest frequency to be accurately reconstructed."},
    {"subject": "Signal Processing", "title": "FIR filter",
     "content": "An FIR (Finite Impulse Response) filter is a digital filter whose output depends only on current and past input values, known for being stable and having linear phase."},
    {"subject": "Signal Processing", "title": "Z-transform",
     "content": "The Z-transform converts a discrete-time signal into a complex frequency domain representation, widely used to analyze and design digital filters and control systems."},

    # ---------------- RESEAUX AVANCE ----------------
    {"subject": "Networking", "title": "VLAN",
     "content": "A VLAN (Virtual Local Area Network) is a logical subdivision of a network that groups devices together as if they were on the same physical LAN, improving security and traffic management."},
    {"subject": "Networking", "title": "Network protocol",
     "content": "A network protocol is a set of rules that define how data is formatted, transmitted, and received between devices on a network, such as HTTP, FTP, or SMTP."},
    {"subject": "Networking", "title": "Packet",
     "content": "A packet is a small unit of data transmitted over a network, containing both the actual data (payload) and control information such as source and destination addresses."},

    # ---------------- CYBERSECURITE AVANCE ----------------
    {"subject": "Cybersecurity", "title": "AES encryption",
     "content": "AES (Advanced Encryption Standard) is a widely used symmetric encryption algorithm that encrypts data in fixed-size blocks using a shared secret key, considered highly secure."},
    {"subject": "Cybersecurity", "title": "RSA encryption",
     "content": "RSA is an asymmetric encryption algorithm based on the mathematical difficulty of factoring large prime numbers, using a public key to encrypt and a private key to decrypt."},
    {"subject": "Cybersecurity", "title": "Hashing",
     "content": "Hashing is the process of converting data into a fixed-size string of characters (a hash) using a one-way function, commonly used to verify data integrity and store passwords securely."},
    {"subject": "Cybersecurity", "title": "DDoS attack",
     "content": "A DDoS (Distributed Denial of Service) attack overwhelms a target server or network with massive traffic from multiple sources, making it unavailable to legitimate users."},

    # ---------------- LINUX / OS ----------------
    {"subject": "Operating Systems", "title": "Linux",
     "content": "Linux is a free, open-source operating system kernel first released in 1991, widely used in servers, embedded systems, and as the basis for many distributions like Ubuntu and Debian."},
    {"subject": "Operating Systems", "title": "Linux file permissions",
     "content": "Linux file permissions control read, write, and execute access for the owner, group, and others, typically viewed and modified using commands like chmod and ls -l."},
    {"subject": "Operating Systems", "title": "Process vs thread",
     "content": "A process is an independent program in execution with its own memory space, while a thread is a smaller unit of execution within a process that shares memory with other threads."},
    {"subject": "Operating Systems", "title": "Kernel",
     "content": "The kernel is the core component of an operating system, managing hardware resources (CPU, memory, devices) and providing services to other software."},
    {"subject": "Operating Systems", "title": "Virtual memory",
     "content": "Virtual memory is a memory management technique that gives programs the illusion of a large, continuous memory space, using disk storage to extend physical RAM."},

    # ---------------- CLOUD COMPUTING ----------------
    {"subject": "Cloud Computing", "title": "Cloud computing",
     "content": "Cloud computing is the delivery of computing services (servers, storage, databases, software) over the internet, allowing on-demand access without owning physical infrastructure."},
    {"subject": "Cloud Computing", "title": "IaaS, PaaS, SaaS",
     "content": "IaaS (Infrastructure as a Service) provides virtual computing resources, PaaS (Platform as a Service) provides a development platform, and SaaS (Software as a Service) provides ready-to-use software over the internet."},
    {"subject": "Cloud Computing", "title": "Virtualization",
     "content": "Virtualization is the creation of virtual (rather than physical) versions of computing resources, such as servers or storage, allowing multiple virtual machines to run on one physical machine."},
    {"subject": "Cloud Computing", "title": "Container (Docker)",
     "content": "A container is a lightweight, portable unit that packages an application with all its dependencies, allowing it to run consistently across different environments. Docker is the most popular containerization tool."},
    {"subject": "Cloud Computing", "title": "Scalability",
     "content": "Scalability is a system's ability to handle increasing workloads by adding resources, either vertically (bigger machines) or horizontally (more machines)."},

    # ---------------- DATA SCIENCE ----------------
    {"subject": "Data Science", "title": "Data science",
     "content": "Data science is an interdisciplinary field that uses statistics, programming, and domain knowledge to extract insights and knowledge from structured and unstructured data."},
    {"subject": "Data Science", "title": "Data cleaning",
     "content": "Data cleaning is the process of detecting and correcting (or removing) corrupt, inaccurate, or incomplete data from a dataset before analysis."},
    {"subject": "Data Science", "title": "Data visualization",
     "content": "Data visualization is the graphical representation of data (charts, graphs, maps) used to help identify patterns, trends, and insights more easily than raw numbers."},
    {"subject": "Data Science", "title": "Correlation vs causation",
     "content": "Correlation means two variables change together, while causation means one variable directly causes a change in another. Correlation does not necessarily imply causation."},

    # ---------------- BASES DE DONNEES ----------------
    {"subject": "Databases", "title": "Relational database",
     "content": "A relational database stores data in tables with rows and columns, linked by relationships between keys, and is queried using SQL (Structured Query Language)."},
    {"subject": "Databases", "title": "SQL",
     "content": "SQL (Structured Query Language) is a standard programming language used to manage and query data in relational databases, using commands like SELECT, INSERT, and UPDATE."},
    {"subject": "Databases", "title": "NoSQL database",
     "content": "A NoSQL database is a non-relational database designed for flexible, scalable storage of unstructured or semi-structured data, such as MongoDB (document-based) or Redis (key-value)."},
    {"subject": "Databases", "title": "Primary key",
     "content": "A primary key is a column (or set of columns) in a database table that uniquely identifies each row, ensuring no duplicate or null values."},

    # ---------------- DEVELOPPEMENT WEB ----------------
    {"subject": "Web Development", "title": "Frontend vs backend",
     "content": "Frontend development focuses on the user interface and experience (what users see, using HTML, CSS, JavaScript), while backend development handles server logic, databases, and APIs."},
    {"subject": "Web Development", "title": "HTTP",
     "content": "HTTP (HyperText Transfer Protocol) is the foundational protocol used to transfer data between web browsers and servers, forming the basis of communication on the web."},
    {"subject": "Web Development", "title": "API",
     "content": "An API (Application Programming Interface) is a set of rules that allows different software applications to communicate with each other, often used to exchange data between systems."},
    {"subject": "Web Development", "title": "REST API",
     "content": "A REST API is a web API that follows REST (Representational State Transfer) principles, using standard HTTP methods (GET, POST, PUT, DELETE) to interact with resources."},

    # ---------------- DEVELOPPEMENT MOBILE ----------------
    {"subject": "Mobile Development", "title": "Native vs cross-platform apps",
     "content": "Native mobile apps are built specifically for one platform (iOS or Android) using platform-specific languages, while cross-platform apps (e.g., Flutter, React Native) run on multiple platforms from a single codebase."},
    {"subject": "Mobile Development", "title": "Mobile app lifecycle",
     "content": "The mobile app lifecycle refers to the different states an app goes through (launching, running, paused, background, terminated), managed by the operating system to optimize resource usage."},

    # ---------------- DEVOPS ----------------
    {"subject": "DevOps", "title": "DevOps",
     "content": "DevOps is a set of practices combining software development (Dev) and IT operations (Ops) to shorten the development lifecycle and deliver software more frequently and reliably."},
    {"subject": "DevOps", "title": "CI/CD",
     "content": "CI/CD (Continuous Integration / Continuous Deployment) is a DevOps practice that automates building, testing, and deploying code changes frequently and reliably."},
    {"subject": "DevOps", "title": "Version control (Git)",
     "content": "Version control is a system that tracks changes to code over time, allowing collaboration and history tracking. Git is the most widely used version control system, often paired with GitHub."},

    # ---------------- GENIE LOGICIEL ----------------
    {"subject": "Software Engineering", "title": "Agile methodology",
     "content": "Agile is a software development methodology based on iterative development, collaboration, and flexibility, breaking work into small cycles called sprints (often used with Scrum)."},
    {"subject": "Software Engineering", "title": "Scrum",
     "content": "Scrum is an Agile framework for managing software projects, organized around fixed-length sprints, daily stand-up meetings, and defined roles like Product Owner and Scrum Master."},
    {"subject": "Software Engineering", "title": "Unit testing",
     "content": "Unit testing is the practice of testing individual components or functions of code in isolation, to verify they work correctly before integrating them into the full system."},

    # ---------------- NLP ----------------
    {"subject": "NLP", "title": "Natural Language Processing (NLP)",
     "content": "Natural Language Processing (NLP) is a field of AI focused on enabling computers to understand, interpret, and generate human language, used in chatbots, translation, and text analysis."},
    {"subject": "NLP", "title": "Word embedding",
     "content": "A word embedding is a numerical vector representation of a word that captures its meaning based on context, allowing similar words to have similar vector representations."},
    {"subject": "NLP", "title": "Sentiment analysis",
     "content": "Sentiment analysis is an NLP technique used to determine the emotional tone (positive, negative, neutral) of a piece of text, commonly used to analyze reviews or social media posts."},

    # ---------------- SYSTEMES EMBARQUES ----------------
    {"subject": "Embedded Systems", "title": "Embedded system",
     "content": "An embedded system is a combination of computer hardware and software designed to perform a specific function within a larger device, such as in cars, appliances, or medical equipment."},
    {"subject": "Embedded Systems", "title": "Real-time operating system (RTOS)",
     "content": "A Real-Time Operating System (RTOS) is an operating system designed to process data and respond to events within strict, predictable time constraints, commonly used in embedded systems."},
    {"subject": "Embedded Systems", "title": "GPIO",
     "content": "GPIO (General-Purpose Input/Output) refers to programmable pins on a microcontroller or embedded board that can be configured as digital inputs or outputs to interact with external circuits."},

    # ---------------- IA : SOUS-DOMAINES ----------------
    {"subject": "Artificial Intelligence", "title": "Computer vision",
     "content": "Computer vision is a field of AI that enables computers to interpret and understand visual information from images or videos, used in applications like facial recognition and self-driving cars."},
    {"subject": "Artificial Intelligence", "title": "Generative AI",
     "content": "Generative AI refers to AI systems capable of creating new content, such as text, images, or audio, based on patterns learned from training data. Examples include ChatGPT and image generators like DALL-E."},
    {"subject": "Artificial Intelligence", "title": "Reinforcement learning",
     "content": "Reinforcement learning is a machine learning approach where an agent learns to make decisions by taking actions in an environment and receiving rewards or penalties, aiming to maximize cumulative reward."},

    # ---------------- LANGAGES DE PROGRAMMATION ----------------
    {"subject": "Computer Science", "title": "C programming language",
     "content": "C is a general-purpose, low-level programming language created in 1972, known for its efficiency and direct access to memory, widely used in operating systems and embedded systems."},
    {"subject": "Computer Science", "title": "Python programming language",
     "content": "Python is a high-level, general-purpose programming language known for its readable syntax, widely used in web development, data science, automation, and artificial intelligence."},
    {"subject": "Computer Science", "title": "Java programming language",
     "content": "Java is an object-oriented programming language designed to run on any platform via the Java Virtual Machine (JVM), widely used in enterprise applications and Android development."},

    # ---------------- CYBERSECURITE : SOUS-DOMAINES ----------------
    {"subject": "Cybersecurity", "title": "Cryptography",
     "content": "Cryptography is the practice of securing communication and data by transforming it into unreadable formats, using techniques like encryption, to protect confidentiality and integrity."},
    {"subject": "Cybersecurity", "title": "Network security",
     "content": "Network security involves protecting computer networks from unauthorized access, misuse, or attacks, using tools like firewalls, intrusion detection systems, and VPNs."},
    {"subject": "Cybersecurity", "title": "Web security",
     "content": "Web security focuses on protecting websites and web applications from threats such as SQL injection, cross-site scripting (XSS), and other vulnerabilities that could compromise data or users."},
    {"subject": "Cybersecurity", "title": "Malware",
     "content": "Malware (malicious software) is any software designed to harm, exploit, or gain unauthorized access to a computer system, including viruses, worms, trojans, and ransomware."},
    {"subject": "Cybersecurity", "title": "Digital forensics",
     "content": "Digital forensics is the process of collecting, analyzing, and preserving digital evidence from computers or networks, often used to investigate cybercrimes."},
    {"subject": "Cybersecurity", "title": "Ethical hacking",
     "content": "Ethical hacking is the authorized practice of testing computer systems for security vulnerabilities, using the same techniques as malicious hackers but with permission, to help improve security."},

    # ---------------- CULTURE GENERALE ----------------
    {"subject": "General Knowledge", "title": "United Nations",
     "content": "The United Nations (UN) is an international organization founded in 1945, currently with 193 member states, working to maintain peace, security, and cooperation among countries."},
    {"subject": "General Knowledge", "title": "Olympic Games",
     "content": "The Olympic Games are an international multi-sport event held every four years, alternating between Summer and Winter Games, tracing its origins to ancient Greece."},
    {"subject": "General Knowledge", "title": "World Wide Web",
     "content": "The World Wide Web was invented by Tim Berners-Lee in 1989, providing a system of interlinked documents accessed via the internet, distinct from the internet itself which is the underlying network."},
    {"subject": "General Knowledge", "title": "Nobel Prize",
     "content": "The Nobel Prize is an international award given annually in fields such as Physics, Chemistry, Medicine, Literature, Peace, and Economics, established by Alfred Nobel's will in 1895."},

    # ---------------- LOGIQUE / RAISONNEMENT ----------------
    {"subject": "Logic", "title": "Deductive reasoning",
     "content": "Deductive reasoning is a logical process where a conclusion is drawn from general premises that are assumed to be true, guaranteeing the conclusion is true if the premises are true."},
    {"subject": "Logic", "title": "Inductive reasoning",
     "content": "Inductive reasoning is a logical process where a general conclusion is drawn from specific observations or examples, offering probable but not guaranteed truth."},
    {"subject": "Logic", "title": "Boolean logic",
     "content": "Boolean logic is a form of algebra where variables have only two possible values, true or false (1 or 0), using operators like AND, OR, and NOT, fundamental to digital circuits and programming."},
    {"subject": "Logic", "title": "Syllogism",
     "content": "A syllogism is a form of logical reasoning with two premises and a conclusion, such as: 'All men are mortal. Socrates is a man. Therefore, Socrates is mortal.'"},

    # ---------------- ECONOMIE / FINANCE ----------------
    {"subject": "Economics", "title": "Supply and demand",
     "content": "Supply and demand is an economic model explaining how the price of a good is determined by the relationship between its availability (supply) and how much people want it (demand)."},
    {"subject": "Economics", "title": "Inflation",
     "content": "Inflation is the general increase in prices of goods and services over time, resulting in a decrease in the purchasing power of money."},
    {"subject": "Economics", "title": "GDP",
     "content": "GDP (Gross Domestic Product) is the total monetary value of all goods and services produced within a country over a specific period, used as a key indicator of economic performance."},
    {"subject": "Economics", "title": "Startup",
     "content": "A startup is a newly founded company, typically in its early stages, aiming to develop a scalable business model, often around an innovative product, service, or technology."},

    # ---------------- DROIT ----------------
    {"subject": "Law", "title": "Intellectual property",
     "content": "Intellectual property refers to legal rights protecting creations of the mind, such as inventions (patents), literary and artistic works (copyright), and brand names (trademarks)."},
    {"subject": "Law", "title": "GDPR",
     "content": "The GDPR (General Data Protection Regulation) is a European Union law, effective since 2018, that regulates how organizations collect, store, and process personal data of EU citizens."},
    {"subject": "Law", "title": "Contract",
     "content": "A contract is a legally binding agreement between two or more parties, creating obligations that are enforceable by law, requiring an offer, acceptance, and mutual consent."},

    # ---------------- BIOLOGIE ----------------
    {"subject": "Biology", "title": "Cell",
     "content": "A cell is the basic structural and functional unit of all living organisms, either prokaryotic (without a nucleus, like bacteria) or eukaryotic (with a nucleus, like human cells)."},
    {"subject": "Biology", "title": "DNA",
     "content": "DNA (Deoxyribonucleic Acid) is a molecule that carries the genetic instructions for the development, functioning, and reproduction of all known living organisms."},
    {"subject": "Biology", "title": "Photosynthesis",
     "content": "Photosynthesis is the process by which plants, algae, and some bacteria convert sunlight, water, and carbon dioxide into glucose (energy) and oxygen."},
    {"subject": "Biology", "title": "Human genome",
     "content": "The human genome is the complete set of genetic information (DNA) in a human being, consisting of approximately 3 billion base pairs organized into 23 pairs of chromosomes."},
    {"subject": "Biology", "title": "Evolution",
     "content": "Evolution is the process by which species of organisms change over successive generations through mechanisms such as natural selection, first extensively described by Charles Darwin."},

    # ---------------- OUTILS CLOUD PRECIS ----------------
    {"subject": "Cloud Computing", "title": "AWS",
     "content": "AWS (Amazon Web Services) is the leading cloud computing platform, offering services like EC2 (virtual servers), S3 (storage), and Lambda (serverless computing)."},
    {"subject": "Cloud Computing", "title": "Microsoft Azure",
     "content": "Microsoft Azure is a cloud computing platform offering a wide range of services including virtual machines, databases, and AI tools, widely used in enterprise environments."},
    {"subject": "Cloud Computing", "title": "Google Cloud Platform",
     "content": "Google Cloud Platform (GCP) is Google's cloud computing service, offering infrastructure, data analytics, and machine learning tools such as BigQuery and Vertex AI."},
    {"subject": "Cloud Computing", "title": "Kubernetes",
     "content": "Kubernetes is an open-source platform for automating the deployment, scaling, and management of containerized applications, often used alongside Docker."},

    # ---------------- LINUX / BASH PRECIS ----------------
    {"subject": "Operating Systems", "title": "Bash shell",
     "content": "Bash (Bourne Again SHell) is a command-line interpreter widely used on Linux and macOS, allowing users to run commands and write scripts to automate tasks."},
    {"subject": "Operating Systems", "title": "Common Linux commands",
     "content": "Common Linux commands include 'ls' (list files), 'cd' (change directory), 'grep' (search text), 'chmod' (change permissions), and 'sudo' (run as administrator)."},

    # ---------------- BASES DE DONNEES PRECIS ----------------
    {"subject": "Databases", "title": "MySQL",
     "content": "MySQL is a popular open-source relational database management system, widely used in web applications, known for its speed and reliability."},
    {"subject": "Databases", "title": "PostgreSQL",
     "content": "PostgreSQL is a powerful open-source relational database management system known for its advanced features, standards compliance, and support for complex queries."},
    {"subject": "Databases", "title": "MongoDB",
     "content": "MongoDB is a popular NoSQL database that stores data in flexible, JSON-like documents rather than tables, well-suited for unstructured or rapidly changing data."},

    # ---------------- WEB : OUTILS PRECIS ----------------
    {"subject": "Web Development", "title": "HTML",
     "content": "HTML (HyperText Markup Language) is the standard markup language used to structure content on web pages, defining elements like headings, paragraphs, and links."},
    {"subject": "Web Development", "title": "CSS",
     "content": "CSS (Cascading Style Sheets) is a language used to style and layout HTML content, controlling colors, fonts, spacing, and responsive design."},
    {"subject": "Web Development", "title": "JavaScript",
     "content": "JavaScript is a programming language that enables interactive and dynamic behavior on web pages, running in the browser and also on servers via Node.js."},
    {"subject": "Web Development", "title": "React",
     "content": "React is a popular JavaScript library for building user interfaces, developed by Facebook, based on reusable components and a virtual DOM for efficient rendering."},

    # ---------------- MOBILE : OUTILS PRECIS ----------------
    {"subject": "Mobile Development", "title": "Android",
     "content": "Android is a mobile operating system developed by Google, based on the Linux kernel, powering the majority of smartphones worldwide."},
    {"subject": "Mobile Development", "title": "Flutter",
     "content": "Flutter is an open-source UI framework developed by Google, using the Dart language, allowing developers to build natively compiled apps for mobile, web, and desktop from a single codebase."},
    {"subject": "Mobile Development", "title": "Kotlin",
     "content": "Kotlin is a modern, statically typed programming language, officially recommended by Google for native Android app development, fully interoperable with Java."},

    # ---------------- ANGLAIS ----------------
    {"subject": "English", "title": "Parts of speech",
     "content": "The main parts of speech in English are nouns, verbs, adjectives, adverbs, pronouns, prepositions, conjunctions, and interjections, each serving a different grammatical role in a sentence."},
    {"subject": "English", "title": "Present simple vs present continuous",
     "content": "The present simple is used for habits and general facts (e.g., 'She works here'), while the present continuous describes actions happening now (e.g., 'She is working now')."},
    {"subject": "English", "title": "Synonym and antonym",
     "content": "A synonym is a word with a similar meaning to another word (e.g., 'happy' and 'glad'), while an antonym is a word with the opposite meaning (e.g., 'happy' and 'sad')."},

    # ---------------- FRANCAIS ----------------
    {"subject": "French", "title": "Les temps verbaux de base",
     "content": "Les temps verbaux de base en français incluent le présent, le passé composé, l'imparfait et le futur simple, chacun exprimant une relation différente au temps de l'action."},
    {"subject": "French", "title": "Accord du participe passé",
     "content": "Le participe passé s'accorde en genre et en nombre avec le sujet lorsqu'il est employé avec l'auxiliaire être, mais reste généralement invariable avec l'auxiliaire avoir, sauf exceptions."},
    {"subject": "French", "title": "Les articles en français",
     "content": "Le français utilise des articles définis (le, la, les), indéfinis (un, une, des), et partitifs (du, de la, des) pour introduire les noms selon leur genre, nombre et degré de précision."},

    # ---------------- MEDECINE ----------------
    {"subject": "Medicine", "title": "Immune system",
     "content": "The immune system is the body's defense network against pathogens like bacteria and viruses, made up of white blood cells, antibodies, and organs such as the thymus and spleen. Here is how the immune system works: it first detects foreign pathogens, then white blood cells attack and destroy the invaders, antibodies are produced to neutralize them, and memory cells are created so the body can respond faster if the same pathogen returns."},
    {"subject": "Medicine", "title": "Vaccine",
     "content": "A vaccine is a biological preparation that trains the immune system to recognize and fight a specific pathogen. The purpose of vaccines is to prevent disease by preparing the body's defenses in advance, typically using a weakened, inactivated, or partial form of the pathogen."},
    {"subject": "Medicine", "title": "Antibiotic",
     "content": "An antibiotic is a medicine that kills or stops the growth of bacteria, used to treat bacterial infections. Antibiotics are not effective against viruses."},
    {"subject": "Medicine", "title": "Blood types",
     "content": "Human blood is classified into four main types (A, B, AB, O), each with a positive or negative Rh factor, determined by specific antigens on red blood cells."},
    {"subject": "Medicine", "title": "Cardiovascular system",
     "content": "The cardiovascular system consists of the heart, blood vessels, and blood, responsible for circulating oxygen, nutrients, and waste products throughout the body."},
    {"subject": "Medicine", "title": "Nervous system",
     "content": "The nervous system, made up of the brain, spinal cord, and nerves, controls body functions by transmitting electrical signals between the brain and the rest of the body."},
    {"subject": "Medicine", "title": "Viral infection vs bacterial infection",
     "content": "A viral infection is caused by a virus, which needs a host cell to reproduce and cannot be treated with antibiotics, while a bacterial infection is caused by bacteria, living organisms that can often be treated with antibiotics. Viral examples include the flu and COVID-19; bacterial examples include strep throat and tuberculosis."},

    # ---------------- SCIENCES DE LA VIE ET DE LA TERRE (SVT) ----------------
    {"subject": "Earth Science", "title": "Plate tectonics",
     "content": "Plate tectonics is the scientific theory that Earth's outer shell is divided into several plates that move slowly over the mantle, causing earthquakes, volcanoes, and mountain formation."},
    {"subject": "Earth Science", "title": "Volcano",
     "content": "A volcano is an opening in Earth's crust through which molten rock (magma), ash, and gases escape, often forming a mountain-like structure over time."},
    {"subject": "Earth Science", "title": "Earthquake",
     "content": "An earthquake is a sudden shaking of the ground caused by the movement of tectonic plates or fault lines releasing built-up energy, measured using the Richter or moment magnitude scale."},
    {"subject": "Earth Science", "title": "Water cycle",
     "content": "The water cycle describes the continuous movement of water through evaporation, condensation, precipitation, and collection, circulating between the atmosphere, land, and oceans."},
    {"subject": "Earth Science", "title": "Ecosystem",
     "content": "An ecosystem is a community of living organisms interacting with each other and their physical environment, forming a functional ecological unit."},
    {"subject": "Earth Science", "title": "Food chain",
     "content": "A food chain shows the flow of energy between organisms, starting from producers (plants) to primary consumers (herbivores) to secondary and tertiary consumers (carnivores)."},
    {"subject": "Earth Science", "title": "Biodiversity",
     "content": "Biodiversity refers to the variety of life on Earth, including the diversity of species, genes, and ecosystems, essential for ecological balance and resilience."},
    {"subject": "Earth Science", "title": "Climate change",
     "content": "Climate change refers to long-term shifts in global temperatures and weather patterns, primarily driven since the industrial era by human activities such as burning fossil fuels."},

    # ---------------- MEDECINE : COMPLEMENTS ----------------
    {"subject": "Medicine", "title": "Flu symptoms",
     "content": "Common symptoms of the flu (influenza) include fever, chills, muscle aches, cough, sore throat, fatigue, and headache, typically appearing suddenly and lasting about a week."},
    {"subject": "Medicine", "title": "Diabetes",
     "content": "Diabetes is a chronic condition where the body cannot properly regulate blood sugar levels, either due to insufficient insulin production (Type 1) or insulin resistance (Type 2)."},
    {"subject": "Medicine", "title": "Fever",
     "content": "A fever is a temporary increase in body temperature, usually above 38°C (100.4°F), often a sign that the body is fighting an infection."},
    {"subject": "Medicine", "title": "Kidney failure causes",
     "content": "Kidney failure can be caused by conditions such as diabetes, high blood pressure, chronic kidney disease, severe dehydration, or blockages in the urinary tract that damage kidney function over time."},
    {"subject": "Medicine", "title": "Alzheimer's disease diagnosis",
     "content": "Alzheimer's disease is diagnosed through a combination of medical history review, cognitive tests, neurological exams, brain imaging (MRI or CT scans), and sometimes blood tests to rule out other causes."},
    {"subject": "Medicine", "title": "Heart disease risk factors",
     "content": "Risk factors for heart disease include high blood pressure, high cholesterol, smoking, diabetes, obesity, physical inactivity, poor diet, and a family history of heart disease."},
    {"subject": "Medicine", "title": "Anemia causes",
     "content": "Anemia is commonly caused by iron deficiency, vitamin B12 or folate deficiency, chronic diseases, blood loss, or genetic conditions that affect red blood cell production."},
    {"subject": "Medicine", "title": "MRI vs CT scan",
     "content": "An MRI (Magnetic Resonance Imaging) uses magnetic fields to produce detailed images of soft tissues without radiation, while a CT scan (Computed Tomography) uses X-rays to quickly produce cross-sectional images, better suited for bones and emergencies."},
    {"subject": "Medicine", "title": "LDL vs HDL cholesterol",
     "content": "LDL (Low-Density Lipoprotein) is often called 'bad' cholesterol because it can build up in artery walls, while HDL (High-Density Lipoprotein) is called 'good' cholesterol because it helps remove excess cholesterol from the bloodstream."},
    {"subject": "Medicine", "title": "Heart-healthy foods",
     "content": "Foods good for heart health include fatty fish (omega-3), fruits, vegetables, whole grains, nuts, and olive oil, while reducing saturated fats, salt, and processed sugar supports cardiovascular health."},
    {"subject": "Medicine", "title": "Importance of exercise",
     "content": "Regular exercise is important for health because it strengthens the heart, improves circulation, helps maintain a healthy weight, reduces stress, and lowers the risk of chronic diseases like diabetes and heart disease."},
    {"subject": "Medicine", "title": "Parkinson's disease symptoms",
     "content": "Early symptoms of Parkinson's disease include tremors (shaking), stiffness, slow movement, balance problems, and changes in handwriting or speech."},

    # ---------------- PREMIERS SECOURS ----------------
    {"subject": "First Aid", "title": "Choking response",
     "content": "If someone is choking and cannot breathe, cough, or speak, perform the Heimlich maneuver: stand behind them, place a fist above their navel, and give quick upward thrusts until the object is expelled."},
    {"subject": "First Aid", "title": "Severe bleeding response",
     "content": "For severe bleeding, apply firm, direct pressure to the wound with a clean cloth, keep the injured area elevated if possible, and call emergency services immediately if bleeding does not stop."},
    {"subject": "First Aid", "title": "Stroke warning signs",
     "content": "Warning signs of a stroke can be remembered with FAST: Face drooping, Arm weakness, Speech difficulty, and Time to call emergency services immediately, as fast treatment is critical."},
    {"subject": "First Aid", "title": "When to call emergency services",
     "content": "Call emergency medical services immediately for symptoms like chest pain, difficulty breathing, severe bleeding, loss of consciousness, signs of stroke, or any life-threatening situation."},

    # ---------------- ECONOMIE : COMPLEMENTS ----------------
    {"subject": "Economics", "title": "Interest rates and the economy",
     "content": "Interest rates affect the economy by influencing borrowing costs: higher rates discourage spending and investment (slowing the economy), while lower rates encourage borrowing and spending (stimulating growth)."},
    {"subject": "Economics", "title": "Unemployment causes",
     "content": "Unemployment can be caused by economic recessions, technological automation replacing jobs, seasonal industry changes, mismatched skills, or structural shifts in the economy."},

    # ---------------- RESEAUX : COMPLEMENTS ----------------
    {"subject": "Networking", "title": "Subnet mask",
     "content": "A subnet mask is a number that divides an IP address into network and host portions, used to determine which devices belong to the same local network."},

    # ---------------- DATA SCIENCE : COMPLEMENTS ----------------
    {"subject": "Data Science", "title": "Feature engineering",
     "content": "Feature engineering is the process of selecting, transforming, or creating input variables (features) from raw data to improve the performance of a machine learning model."},
    {"subject": "Data Science", "title": "Mean, median, and mode",
     "content": "The mean is the average of a dataset, the median is the middle value when data is sorted, and the mode is the most frequently occurring value in the dataset."},
    {"subject": "Data Science", "title": "Qualitative vs quantitative data",
     "content": "Qualitative data describes categories or qualities (e.g., colors, opinions), while quantitative data consists of numerical values that can be measured and analyzed statistically (e.g., height, age)."},

    # ---------------- MATHS : COMPLEMENTS ----------------
    {"subject": "Math", "title": "Permutation vs combination",
     "content": "A permutation is an arrangement of items where order matters, while a combination is a selection of items where order does not matter."},

    # ---------------- INFORMATIQUE : COMPLEMENTS ----------------
    {"subject": "Computer Science", "title": "Stack vs queue",
     "content": "A stack is a data structure that follows Last-In-First-Out (LIFO) order, while a queue follows First-In-First-Out (FIFO) order, both used to manage collections of elements."},

    # ---------------- LOGISTIQUE (NOUVELLE MATIERE) ----------------
    {"subject": "Logistics", "title": "Supply chain management",
     "content": "Supply chain management is the coordination of all activities involved in producing and delivering a product, from raw materials to the final customer, including sourcing, production, and distribution."},
    {"subject": "Logistics", "title": "Inventory management",
     "content": "Inventory management is the process of ordering, storing, tracking, and controlling a company's stock of goods to ensure the right amount of inventory is available without excess or shortage."},
    {"subject": "Logistics", "title": "Logistics vs supply chain management",
     "content": "Logistics focuses specifically on the movement and storage of goods (transportation, warehousing), while supply chain management is a broader concept covering the entire process from sourcing raw materials to delivering the final product."},
    {"subject": "Logistics", "title": "Just-in-time (JIT) inventory",
     "content": "Just-in-time (JIT) is an inventory strategy where materials or products are ordered and received only as needed for production, reducing storage costs but requiring precise coordination."},
    {"subject": "Logistics", "title": "Role of a warehouse",
     "content": "A warehouse stores goods between production and distribution, serving as a hub for inventory management, order fulfillment, and efficient distribution to retailers or customers."},

    # ---------------- COMPLEMENTS FINAUX ----------------
    {"subject": "Medicine", "title": "Heart attack warning signs",
     "content": "The first signs of a heart attack often include chest pain or pressure, pain spreading to the arm, jaw, or back, shortness of breath, cold sweats, nausea, and lightheadedness."},
    {"subject": "Medicine", "title": "Stress and physical health",
     "content": "Chronic stress can negatively affect physical health by raising blood pressure, weakening the immune system, disrupting sleep, and increasing the risk of heart disease, digestive issues, and mental health problems."},
    {"subject": "Physics", "title": "Electromagnetic radiation",
     "content": "Electromagnetic radiation is a form of energy that travels through space as waves, including visible light, radio waves, X-rays, and microwaves, all traveling at the speed of light."},

    # ---------------- INFORMATIQUE / PROGRAMMATION ----------------
    {"subject": "Computer Science", "title": "Algorithm",
     "content": "An algorithm is a finite sequence of well-defined instructions used to solve a problem or perform a computation, forming the basis of computer programs."},
    {"subject": "Computer Science", "title": "Array",
     "content": "An array is a data structure that stores a fixed-size collection of elements of the same type, accessed using an index, typically starting at 0."},
    {"subject": "Computer Science", "title": "Linked list",
     "content": "A linked list is a data structure consisting of nodes, where each node contains data and a reference (pointer) to the next node in the sequence."},
    {"subject": "Computer Science", "title": "Binary search",
     "content": "Binary search is an efficient algorithm for finding an element in a sorted array by repeatedly dividing the search interval in half, with a time complexity of O(log n)."},
    {"subject": "Computer Science", "title": "Object-oriented programming",
     "content": "Object-oriented programming (OOP) is a programming paradigm based on objects that contain data (attributes) and code (methods), built around concepts like classes, inheritance, and polymorphism."},
    {"subject": "Computer Science", "title": "Time complexity",
     "content": "Time complexity describes how the runtime of an algorithm grows as the input size increases, commonly expressed using Big O notation, such as O(n) or O(n^2)."},
    {"subject": "Computer Science", "title": "Recursion",
     "content": "Recursion is a programming technique where a function calls itself to solve smaller instances of the same problem, until reaching a base case."},

    # ---------------- CYBERSECURITE ----------------
    {"subject": "Cybersecurity", "title": "Encryption",
     "content": "Encryption is the process of converting readable data (plaintext) into an unreadable format (ciphertext) using an algorithm and a key, to protect its confidentiality."},
    {"subject": "Cybersecurity", "title": "Symmetric vs asymmetric encryption",
     "content": "Symmetric encryption uses the same key for encryption and decryption, while asymmetric encryption uses a pair of public and private keys."},
    {"subject": "Cybersecurity", "title": "Firewall",
     "content": "A firewall is a network security device or software that monitors and filters incoming and outgoing network traffic based on predefined security rules."},
    {"subject": "Cybersecurity", "title": "Phishing",
     "content": "Phishing is a type of cyberattack where attackers impersonate legitimate entities, typically through email or fake websites, to trick victims into revealing sensitive information."},
    {"subject": "Cybersecurity", "title": "VPN",
     "content": "A VPN (Virtual Private Network) creates an encrypted connection over a public network, allowing users to send and receive data securely as if connected to a private network."},
    {"subject": "Cybersecurity", "title": "SQL injection",
     "content": "SQL injection is a code injection attack where malicious SQL statements are inserted into an application's input fields to manipulate or access its database."},
    {"subject": "Cybersecurity", "title": "Two-factor authentication",
     "content": "Two-factor authentication (2FA) is a security process that requires two different forms of identification, typically a password plus a code sent to a device, to verify a user's identity."},

    # ---------------- CHIMIE ----------------
    {"subject": "Chemistry", "title": "Atom",
     "content": "An atom is the basic unit of matter, consisting of a nucleus (protons and neutrons) surrounded by electrons. It is the smallest unit that retains the properties of a chemical element."},
    {"subject": "Chemistry", "title": "Periodic table",
     "content": "The periodic table is a chart that organizes all known chemical elements by increasing atomic number, grouped by similar chemical properties."},
    {"subject": "Chemistry", "title": "Chemical bond",
     "content": "A chemical bond is the attraction between atoms that allows them to form molecules. Common types include covalent bonds (sharing electrons) and ionic bonds (transferring electrons)."},
    {"subject": "Chemistry", "title": "pH scale",
     "content": "The pH scale measures how acidic or basic a solution is, ranging from 0 (very acidic) to 14 (very basic), with 7 being neutral (like pure water)."},
    {"subject": "Chemistry", "title": "Water molecule",
     "content": "Water (H2O) is a molecule made of two hydrogen atoms covalently bonded to one oxygen atom, essential for all known forms of life."},
    {"subject": "Chemistry", "title": "Chemical reaction",
     "content": "A chemical reaction is a process in which one or more substances (reactants) are transformed into different substances (products), involving the breaking and forming of chemical bonds."},
]
