# ============================================================
# BASE DE CONNAISSANCES POUR LE RAG
# Fiches courtes et factuellement vérifiées, par matière.
# ============================================================

KNOWLEDGE_BASE = [
    # ---------------- MATHS ----------------
    {"subject": "Math", "title": "Pythagorean theorem",
     "content": "The Pythagorean theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the other two sides: a^2 + b^2 = c^2."},
    {"subject": "Math", "title": "Derivative",
     "content": "A derivative measures how a function changes as its input changes. It represents the slope of the tangent line to the function's graph at a given point."},
    {"subject": "Math", "title": "Integral",
     "content": "An integral represents the area under the curve of a function. It is the reverse operation of differentiation."},
    {"subject": "Math", "title": "Prime number",
     "content": "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself. Examples include 2, 3, 5, 7, 11."},
    {"subject": "Math", "title": "Pi",
     "content": "Pi (denoted by the Greek letter pi) is the ratio of a circle's circumference to its diameter, approximately equal to 3.14159."},
    {"subject": "Math", "title": "Matrix",
     "content": "A matrix is a rectangular array of numbers arranged in rows and columns, used to represent linear transformations and solve systems of linear equations."},
    {"subject": "Math", "title": "Probability",
     "content": "Probability is a measure of the likelihood that an event will occur, expressed as a number between 0 (impossible) and 1 (certain)."},

    # ---------------- PHYSIQUE ----------------
    {"subject": "Physics", "title": "Newton's first law",
     "content": "Newton's first law states that an object at rest stays at rest, and an object in motion stays in motion at constant velocity, unless acted upon by an external force."},
    {"subject": "Physics", "title": "Newton's second law",
     "content": "Newton's second law states that force equals mass times acceleration (F = m x a)."},
    {"subject": "Physics", "title": "Ohm's law",
     "content": "Ohm's law states that the current through a conductor is directly proportional to the voltage and inversely proportional to the resistance: V = I x R."},
    {"subject": "Physics", "title": "Energy conservation",
     "content": "The law of conservation of energy states that energy cannot be created or destroyed, only transformed from one form to another."},
    {"subject": "Physics", "title": "Speed of light",
     "content": "The speed of light in a vacuum is approximately 299,792 kilometers per second (about 300,000 km/s), the fastest speed possible in the universe."},
    {"subject": "Physics", "title": "Gravity",
     "content": "Gravity is the force of attraction between two masses. On Earth, gravitational acceleration is approximately 9.81 meters per second squared."},
    {"subject": "Physics", "title": "Electric current",
     "content": "Electric current is the flow of electric charge, measured in amperes (A). It flows through a conductor when there is a difference in electric potential."},
    {"subject": "Physics", "title": "Wavelength and frequency",
     "content": "Wavelength is the distance between two consecutive peaks of a wave, while frequency is the number of wave cycles per second, measured in hertz (Hz). Speed = wavelength x frequency."},

    # ---------------- GEOGRAPHIE ----------------
    {"subject": "Geography", "title": "Continents",
     "content": "There are seven continents on Earth: Africa, Antarctica, Asia, Australia, Europe, North America, and South America."},
    {"subject": "Geography", "title": "Largest ocean",
     "content": "The Pacific Ocean is the largest and deepest ocean on Earth, covering about one-third of the planet's surface."},
    {"subject": "Geography", "title": "Longest river",
     "content": "The Nile River, located in Africa, is generally considered the longest river in the world, flowing through Egypt, Sudan, and other countries."},
    {"subject": "Geography", "title": "Highest mountain",
     "content": "Mount Everest, located in the Himalayas on the border of Nepal and China (Tibet), is the highest mountain above sea level at 8,849 meters."},
    {"subject": "Geography", "title": "Sahara Desert",
     "content": "The Sahara is the largest hot desert in the world, covering most of North Africa, including parts of Tunisia, Algeria, Libya, and Morocco."},
    {"subject": "Geography", "title": "Mediterranean Sea",
     "content": "The Mediterranean Sea is a sea connected to the Atlantic Ocean, surrounded by Europe, North Africa, and the Middle East. Tunisia has a long Mediterranean coastline."},

    # ---------------- CIVILISATION / HISTOIRE ----------------
    {"subject": "Civilization", "title": "Ancient Carthage",
     "content": "Carthage was an ancient civilization located in what is now Tunisia, founded by the Phoenicians around the 9th century BC. It became a major power in the Mediterranean before being destroyed by Rome in 146 BC."},
    {"subject": "Civilization", "title": "Ancient Egypt",
     "content": "Ancient Egypt was a civilization along the Nile River, known for its pyramids, pharaohs, and hieroglyphic writing system, flourishing for over 3000 years."},
    {"subject": "Civilization", "title": "Roman Empire",
     "content": "The Roman Empire was one of the largest empires in ancient history, centered in Rome, spanning from Britain to North Africa and the Middle East at its peak."},
    {"subject": "Civilization", "title": "Industrial Revolution",
     "content": "The Industrial Revolution, starting in Britain in the late 18th century, was a period of major industrialization and innovation, transitioning from manual production to machine manufacturing."},
    {"subject": "Civilization", "title": "Tunisian independence",
     "content": "Tunisia gained independence from France on March 20, 1956, ending the French protectorate that had lasted since 1881."},
    {"subject": "Civilization", "title": "Internet invention",
     "content": "The internet originated from ARPANET, a project developed by the US Department of Defense in the late 1960s, and evolved into the modern global network we use today."},

    # ---------------- ELECTRONIQUE / TELECOMS ----------------
    {"subject": "Electronics", "title": "Voltage",
     "content": "Voltage is the electric potential difference between two points, measured in volts (V). It represents the force that pushes electric charge through a circuit."},
    {"subject": "Electronics", "title": "Resistance",
     "content": "Electrical resistance is the opposition to the flow of electric current in a conductor, measured in ohms. It is calculated using Ohm's law: R = V / I."},
    {"subject": "Electronics", "title": "Capacitor",
     "content": "A capacitor is an electronic component that stores electrical energy in an electric field, made of two conductive plates separated by an insulator, measured in farads (F)."},
    {"subject": "Electronics", "title": "Transistor",
     "content": "A transistor is a semiconductor device used to amplify or switch electronic signals. It is a fundamental building block of modern electronic devices and integrated circuits."},
    {"subject": "Electronics", "title": "Signal modulation",
     "content": "Modulation is the process of varying a carrier signal's properties (amplitude, frequency, or phase) to encode information for transmission, used in radio and telecommunications."},
    {"subject": "Electronics", "title": "Analog vs digital signal",
     "content": "An analog signal is continuous and can take any value over a range, while a digital signal is discrete, represented as binary values (0 and 1)."},
    {"subject": "Electronics", "title": "Bandwidth",
     "content": "Bandwidth is the range of frequencies a communication channel can carry, or the maximum data transfer rate of a network connection, typically measured in hertz or bits per second."},
    {"subject": "Electronics", "title": "Antenna",
     "content": "An antenna is a device that converts electrical signals into electromagnetic waves for wireless transmission, and vice versa for reception."},
    {"subject": "Electronics", "title": "Diode",
     "content": "A diode is a semiconductor component that allows electric current to flow in only one direction, commonly used for rectification (converting AC to DC)."},
    {"subject": "Electronics", "title": "Microcontroller",
     "content": "A microcontroller is a compact integrated circuit containing a processor, memory, and input/output peripherals, used to control electronic devices such as PIC or Arduino boards."},
    {"subject": "Electronics", "title": "Analog-to-digital converter (ADC)",
     "content": "An ADC (Analog-to-Digital Converter) converts a continuous analog signal into a discrete digital value, allowing microcontrollers and computers to process real-world signals."},
    {"subject": "Electronics", "title": "Multiplexer",
     "content": "A multiplexer (MUX) is a digital circuit that selects one of several input signals and forwards it to a single output line, based on selector control signals."},
    {"subject": "Electronics", "title": "Flip-flop",
     "content": "A flip-flop is a basic digital circuit that stores one bit of binary data, used as a building block for registers, counters, and memory in digital electronics."},

    # ---------------- RESEAUX / TELECOMS AVANCE ----------------
    {"subject": "Networking", "title": "IP address",
     "content": "An IP address is a unique numerical identifier assigned to each device on a network, used to route data between devices using the Internet Protocol."},
    {"subject": "Networking", "title": "TCP/IP",
     "content": "TCP/IP is the fundamental suite of communication protocols used on the internet, with TCP ensuring reliable data delivery and IP handling addressing and routing."},
    {"subject": "Networking", "title": "OSI model",
     "content": "The OSI model is a conceptual framework that divides network communication into seven layers: Physical, Data Link, Network, Transport, Session, Presentation, and Application."},
    {"subject": "Networking", "title": "DNS",
     "content": "DNS (Domain Name System) translates human-readable domain names (like google.com) into numerical IP addresses that computers use to identify each other."},
    {"subject": "Networking", "title": "Router",
     "content": "A router is a networking device that forwards data packets between different computer networks, directing traffic on the internet and local networks."},
    {"subject": "Networking", "title": "LAN vs WAN",
     "content": "A LAN (Local Area Network) connects devices within a small area like a home or office, while a WAN (Wide Area Network) spans large geographic areas, such as the internet."},
    {"subject": "Networking", "title": "Mobile network generations",
     "content": "Mobile network generations (2G, 3G, 4G, 5G) represent successive advances in wireless technology, each offering higher data speeds and lower latency than the previous one."},
    {"subject": "Networking", "title": "Optical fiber",
     "content": "Optical fiber is a thin strand of glass or plastic that transmits data as pulses of light, offering very high bandwidth and low signal loss over long distances."},

    # ---------------- IA / MACHINE LEARNING ----------------
    {"subject": "Artificial Intelligence", "title": "Machine learning",
     "content": "Machine learning is a field of artificial intelligence where computer systems learn patterns from data to make predictions or decisions, without being explicitly programmed for each task."},
    {"subject": "Artificial Intelligence", "title": "Neural network",
     "content": "A neural network is a machine learning model inspired by the human brain, made of layers of interconnected nodes (neurons) that process and learn from data."},
    {"subject": "Artificial Intelligence", "title": "Deep learning",
     "content": "Deep learning is a subset of machine learning that uses neural networks with many layers to automatically learn complex patterns from large amounts of data."},
    {"subject": "Artificial Intelligence", "title": "Transformer architecture",
     "content": "The Transformer is a neural network architecture introduced in 2017, based on the attention mechanism, forming the foundation of modern language models like GPT and BERT."},
    {"subject": "Artificial Intelligence", "title": "Overfitting",
     "content": "Overfitting occurs when a machine learning model learns the training data too closely, including its noise, resulting in poor performance on new, unseen data."},
    {"subject": "Artificial Intelligence", "title": "Tokenization",
     "content": "Tokenization is the process of splitting text into smaller units (tokens), such as words or subwords, which language models use as their basic input units."},
    {"subject": "Artificial Intelligence", "title": "Fine-tuning",
     "content": "Fine-tuning is the process of taking a pre-trained model and further training it on a smaller, specific dataset to adapt it to a particular task."},
    {"subject": "Artificial Intelligence", "title": "Large Language Model (LLM)",
     "content": "A Large Language Model (LLM) is a type of AI model trained on massive amounts of text data, capable of understanding and generating human-like language, such as GPT or Claude."},

    # ---------------- SIGNAL / DSP (Traitement du Signal) ----------------
    {"subject": "Signal Processing", "title": "Fourier transform",
     "content": "The Fourier transform is a mathematical technique that decomposes a signal into its constituent frequencies, converting a signal from the time domain to the frequency domain."},
    {"subject": "Signal Processing", "title": "Digital Signal Processor (DSP)",
     "content": "A DSP (Digital Signal Processor) is a specialized microprocessor optimized for processing digital signals in real time, such as audio, video, or communication signals."},
    {"subject": "Signal Processing", "title": "Sampling theorem",
     "content": "The Nyquist-Shannon sampling theorem states that a continuous signal must be sampled at a rate at least twice its highest frequency to be accurately reconstructed."},
    {"subject": "Signal Processing", "title": "FIR filter",
     "content": "An FIR (Finite Impulse Response) filter is a digital filter whose output depends only on current and past input values, known for being stable and having linear phase."},
    {"subject": "Signal Processing", "title": "Z-transform",
     "content": "The Z-transform converts a discrete-time signal into a complex frequency domain representation, widely used to analyze and design digital filters and control systems."},

    # ---------------- RESEAUX AVANCE ----------------
    {"subject": "Networking", "title": "VLAN",
     "content": "A VLAN (Virtual Local Area Network) is a logical subdivision of a network that groups devices together as if they were on the same physical LAN, improving security and traffic management."},
    {"subject": "Networking", "title": "Network protocol",
     "content": "A network protocol is a set of rules that define how data is formatted, transmitted, and received between devices on a network, such as HTTP, FTP, or SMTP."},
    {"subject": "Networking", "title": "Packet",
     "content": "A packet is a small unit of data transmitted over a network, containing both the actual data (payload) and control information such as source and destination addresses."},

    # ---------------- CYBERSECURITE AVANCE ----------------
    {"subject": "Cybersecurity", "title": "AES encryption",
     "content": "AES (Advanced Encryption Standard) is a widely used symmetric encryption algorithm that encrypts data in fixed-size blocks using a shared secret key, considered highly secure."},
    {"subject": "Cybersecurity", "title": "RSA encryption",
     "content": "RSA is an asymmetric encryption algorithm based on the mathematical difficulty of factoring large prime numbers, using a public key to encrypt and a private key to decrypt."},
    {"subject": "Cybersecurity", "title": "Hashing",
     "content": "Hashing is the process of converting data into a fixed-size string of characters (a hash) using a one-way function, commonly used to verify data integrity and store passwords securely."},
    {"subject": "Cybersecurity", "title": "DDoS attack",
     "content": "A DDoS (Distributed Denial of Service) attack overwhelms a target server or network with massive traffic from multiple sources, making it unavailable to legitimate users."},

    # ---------------- INFORMATIQUE / PROGRAMMATION ----------------
    {"subject": "Computer Science", "title": "Algorithm",
     "content": "An algorithm is a finite sequence of well-defined instructions used to solve a problem or perform a computation, forming the basis of computer programs."},
    {"subject": "Computer Science", "title": "Array",
     "content": "An array is a data structure that stores a fixed-size collection of elements of the same type, accessed using an index, typically starting at 0."},
    {"subject": "Computer Science", "title": "Linked list",
     "content": "A linked list is a data structure consisting of nodes, where each node contains data and a reference (pointer) to the next node in the sequence."},
    {"subject": "Computer Science", "title": "Binary search",
     "content": "Binary search is an efficient algorithm for finding an element in a sorted array by repeatedly dividing the search interval in half, with a time complexity of O(log n)."},
    {"subject": "Computer Science", "title": "Object-oriented programming",
     "content": "Object-oriented programming (OOP) is a programming paradigm based on objects that contain data (attributes) and code (methods), built around concepts like classes, inheritance, and polymorphism."},
    {"subject": "Computer Science", "title": "Time complexity",
     "content": "Time complexity describes how the runtime of an algorithm grows as the input size increases, commonly expressed using Big O notation, such as O(n) or O(n^2)."},
    {"subject": "Computer Science", "title": "Recursion",
     "content": "Recursion is a programming technique where a function calls itself to solve smaller instances of the same problem, until reaching a base case."},

    # ---------------- CYBERSECURITE ----------------
    {"subject": "Cybersecurity", "title": "Encryption",
     "content": "Encryption is the process of converting readable data (plaintext) into an unreadable format (ciphertext) using an algorithm and a key, to protect its confidentiality."},
    {"subject": "Cybersecurity", "title": "Symmetric vs asymmetric encryption",
     "content": "Symmetric encryption uses the same key for encryption and decryption, while asymmetric encryption uses a pair of public and private keys."},
    {"subject": "Cybersecurity", "title": "Firewall",
     "content": "A firewall is a network security device or software that monitors and filters incoming and outgoing network traffic based on predefined security rules."},
    {"subject": "Cybersecurity", "title": "Phishing",
     "content": "Phishing is a type of cyberattack where attackers impersonate legitimate entities, typically through email or fake websites, to trick victims into revealing sensitive information."},
    {"subject": "Cybersecurity", "title": "VPN",
     "content": "A VPN (Virtual Private Network) creates an encrypted connection over a public network, allowing users to send and receive data securely as if connected to a private network."},
    {"subject": "Cybersecurity", "title": "SQL injection",
     "content": "SQL injection is a code injection attack where malicious SQL statements are inserted into an application's input fields to manipulate or access its database."},
    {"subject": "Cybersecurity", "title": "Two-factor authentication",
     "content": "Two-factor authentication (2FA) is a security process that requires two different forms of identification, typically a password plus a code sent to a device, to verify a user's identity."},

    # ---------------- CHIMIE ----------------
    {"subject": "Chemistry", "title": "Atom",
     "content": "An atom is the basic unit of matter, consisting of a nucleus (protons and neutrons) surrounded by electrons. It is the smallest unit that retains the properties of a chemical element."},
    {"subject": "Chemistry", "title": "Periodic table",
     "content": "The periodic table is a chart that organizes all known chemical elements by increasing atomic number, grouped by similar chemical properties."},
    {"subject": "Chemistry", "title": "Chemical bond",
     "content": "A chemical bond is the attraction between atoms that allows them to form molecules. Common types include covalent bonds (sharing electrons) and ionic bonds (transferring electrons)."},
    {"subject": "Chemistry", "title": "pH scale",
     "content": "The pH scale measures how acidic or basic a solution is, ranging from 0 (very acidic) to 14 (very basic), with 7 being neutral (like pure water)."},
    {"subject": "Chemistry", "title": "Water molecule",
     "content": "Water (H2O) is a molecule made of two hydrogen atoms covalently bonded to one oxygen atom, essential for all known forms of life."},
    {"subject": "Chemistry", "title": "Chemical reaction",
     "content": "A chemical reaction is a process in which one or more substances (reactants) are transformed into different substances (products), involving the breaking and forming of chemical bonds."},
]
